apiVersion: v1
kind: Service
metadata:
  name: nestjs-boilerplate
  labels:
    app: nestjs-boilerplate
spec:
  type: NodePort
  selector:
    app: nestjs-boilerplate
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30300